### ISSUE TITLE
What are pseudo-labels and why do we need them?

### ISSUE THREAD

**Issue by saahiluppal** [DengPingFan/Inf-Net#28]

**Comment by DengPingFan** [comment]
Hi, 
Pseudo-label means the label is generated by our trained model rather than the annotator labeled. It is not necessary for you to use the label if you have enough training data. Currently, our setting is for the semi-supervised learning task. For more details about how to generate the pseudo-label, please check our paper accordingly. 

Best,

**Comment by saahiluppal** [comment]
If pseudo-labels are used while training, then why are we using them for inference?

**Comment by saahiluppal** [comment]
Refer inference script: [here](https://github.com/DengPingFan/Inf-Net/blob/master/MyTest_MulClsLungInf_UNet.py#L46)

**Comment by GewelsJI** [comment]
Hi, @saahiluppal 

I suggest you go deeper into this [reply](https://github.com/DengPingFan/Inf-Net/issues/28#issuecomment-857559844). In other words, the pseudo labels can be served as auxiliary cues during the training/testing under the same semi-supervised learning setting. They should be consistent.

Best regards,
Ge-Peng.

**Comment by saahiluppal** [comment]
I've gone through the code thoroughly and i now understand what's actually happening.
And i was able to successfully execute the inference for all of your models.

Thanks for this awesome project and your support

**Comment by DengPingFan** [comment]
Thanks. Have a nice day.

Best,

Sahil Uppal ***@***.***> 于2021年6月10日周四 下午1:14写道：
